Cuda battery library: battery::string< Allocator > Class Template Reference
battery::string< Allocator > Class Template Reference
#include <string.hpp>
Public Types
using this_type = string< Allocator >
using allocator_type = Allocator
using value_type = char
Public Member Functions
CUDA string (size_t n, const allocator_type &alloc=allocator_type())
CUDA string (const allocator_type &alloc=allocator_type())
CUDA string (const char *raw_string, const allocator_type &alloc=allocator_type())
template<class Allocator2 >
CUDA string (const string< Allocator2 > &other, const allocator_type &alloc=allocator_type())
CUDA string (const string< allocator_type > &other)
string (string< allocator_type > &&other)=default
CUDA string< allocator_type > & operator= (string< allocator_type > other)
HOST string (const std::string &other, const allocator_type &alloc=allocator_type())
CUDA allocator_type get_allocator () const
CUDA size_t size () const
CUDA char & operator[] (size_t i)
CUDA const char & operator[] (size_t i) const
CUDA char * data ()
CUDA const char * data () const
CUDA void print () const
Static Public Member Functions
static CUDA this_type from_int (int x, const allocator_type &alloc=allocator_type())
Friends
template<class Alloc2 >
class string
template<class Alloc1 , class Alloc2 >
CUDA friend bool operator== (const string< Alloc1 > &lhs, const string< Alloc2 > &rhs)
Detailed Description
template<class Allocator = standard_allocator>
class battery::string< Allocator >
string represents a fixed sized array of characters based on vector<char>. All strings are null-terminated.
Member Typedef Documentation
this_type
template<class Allocator = standard_allocator> using battery::string< Allocator >::this_type = string<Allocator>
allocator_type
template<class Allocator = standard_allocator> using battery::string< Allocator >::allocator_type = Allocator
value_type
template<class Allocator = standard_allocator> using battery::string< Allocator >::value_type = char
Constructor & Destructor Documentation
string() [1/7]
template<class Allocator = standard_allocator> CUDA battery::string< Allocator >::string (size_t n, const allocator_type & alloc = allocator_type()) inline
Allocate a string of size n using allocator.
string() [2/7]
template<class Allocator = standard_allocator> CUDA battery::string< Allocator >::string (const allocator_type & alloc = allocator_type()) inline
string() [3/7]
template<class Allocator = standard_allocator> CUDA battery::string< Allocator >::string (const char * raw_string, const allocator_type & alloc = allocator_type()) inline
Allocate a string from raw_string using allocator.
string() [4/7]
template<class Allocator = standard_allocator> template<class Allocator2 > CUDA battery::string< Allocator >::string (const string< Allocator2 > & other, const allocator_type & alloc = allocator_type()) inline
Copy constructor with an allocator.
string() [5/7]
template<class Allocator = standard_allocator> CUDA battery::string< Allocator >::string (const string< allocator_type > & other) inline
Redefine the copy constructor to be sure it calls a constructor with an allocator.
string() [6/7]
template<class Allocator = standard_allocator> battery::string< Allocator >::string (string< allocator_type > && other) default
string() [7/7]
template<class Allocator = standard_allocator> HOST battery::string< Allocator >::string (const std::string< Allocator > & other, const allocator_type & alloc = allocator_type()) inline
Member Function Documentation
operator=()
template<class Allocator = standard_allocator> CUDA string<allocator_type>& battery::string< Allocator >::operator= (string< allocator_type > other) inline
get_allocator()
template<class Allocator = standard_allocator> CUDA allocator_type battery::string< Allocator >::get_allocator () const inline
References battery::vector< T, Allocator >::get_allocator().
Referenced by battery::operator+().
size()
template<class Allocator = standard_allocator> CUDA size_t battery::string< Allocator >::size () const inline
References battery::vector< T, Allocator >::size().
Referenced by battery::operator+(), and battery::string< Allocator >::operator[]().
operator[]() [1/2]
template<class Allocator = standard_allocator> CUDA char& battery::string< Allocator >::operator[] (size_t i) inline
References battery::string< Allocator >::size().
operator[]() [2/2]
template<class Allocator = standard_allocator> CUDA const char& battery::string< Allocator >::operator[] (size_t i) const inline
References battery::string< Allocator >::size().
data() [1/2]
template<class Allocator = standard_allocator> CUDA char* battery::string< Allocator >::data () inline
References battery::vector< T, Allocator >::data().
Referenced by battery::operator+(), battery::operator==(), and battery::string< Allocator >::print().
data() [2/2]
template<class Allocator = standard_allocator> CUDA const char* battery::string< Allocator >::data () const inline
References battery::vector< T, Allocator >::data().
print()
template<class Allocator = standard_allocator> CUDA void battery::string< Allocator >::print () const inline
References battery::string< Allocator >::data().
from_int()
template<class Allocator = standard_allocator> static CUDA this_type battery::string< Allocator >::from_int (int x, const allocator_type & alloc = allocator_type()) inline static
Friends And Related Function Documentation
string
template<class Allocator = standard_allocator> template<class Alloc2 > friend class string friend
operator==
template<class Allocator = standard_allocator> template<class Alloc1 , class Alloc2 > CUDA friend bool operator== (const string< Alloc1 > & lhs, const string< Alloc2 > & rhs) friend
The documentation for this class was generated from the following file:
include/battery/string.hpp