Cuda battery library: battery::bitset< N, Mem, T > Class Template Reference
battery::bitset< N, Mem, T > Class Template Reference
#include <bitset.hpp>
Public Member Functions
constexpr CUDA bitset ()
constexpr CUDA bitset (const char *bit_str)
template<class Mem2 >
constexpr CUDA bitset (const bitset< N, Mem2, T > &other)
constexpr CUDA bool test (size_t pos) const
constexpr CUDA bool all () const
constexpr CUDA bool any () const
constexpr CUDA bool none () const
constexpr CUDA size_t size () const
constexpr CUDA size_t count () const
constexpr CUDA bitset & set ()
constexpr CUDA bitset & set (size_t pos)
constexpr CUDA bitset & set (size_t pos, bool value)
constexpr CUDA bitset & reset ()
constexpr CUDA bitset & reset (size_t pos)
constexpr CUDA bitset & flip ()
constexpr CUDA bitset & flip (size_t pos)
template<class Mem2 >
constexpr CUDA bool is_subset_of (const bitset< N, Mem2, T > &other) const
template<class Mem2 >
constexpr CUDA bool is_proper_subset_of (const bitset< N, Mem2, T > &other) const
template<class Mem2 >
constexpr CUDA bitset & operator&= (const bitset< N, Mem2, T > &other)
template<class Mem2 >
constexpr CUDA bitset & operator|= (const bitset< N, Mem2, T > &other)
template<class Mem2 >
constexpr CUDA bitset & operator^= (const bitset< N, Mem2, T > &other)
constexpr CUDA bitset operator~ () const
template<class Mem2 >
constexpr CUDA bool operator== (const bitset< N, Mem2, T > &other) const
template<class Mem2 >
constexpr CUDA bool operator!= (const bitset< N, Mem2, T > &other) const
constexpr CUDA int countl_zero () const
constexpr CUDA int countl_one () const
constexpr CUDA int countr_zero () const
constexpr CUDA int countr_one () const
constexpr CUDA void print () const
template<class Allocator >
CUDA string< Allocator > to_string (Allocator allocator=Allocator()) const
Static Public Member Functions
static constexpr CUDA bitset zeroes ()
static constexpr CUDA bitset ones ()
Detailed Description
template<size_t N, class Mem, class T = unsigned long long>
class battery::bitset< N, Mem, T >
An extension of the C++ STL bitset class with support for set operations (e.g., union and intersection) and for atomic read and write on the bitset blocks.
Constructor & Destructor Documentation
bitset() [1/3]
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA battery::bitset< N, Mem, T >::bitset () inline constexpr
Referenced by battery::bitset< N, Mem, T >::ones(), battery::bitset< N, Mem, T >::operator~(), and battery::bitset< N, Mem, T >::zeroes().
bitset() [2/3]
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA battery::bitset< N, Mem, T >::bitset (const char * bit_str) inline constexpr
References battery::min(), battery::bitset< N, Mem, T >::set(), and battery::strlen().
bitset() [3/3]
template<size_t N, class Mem , class T = unsigned long long> template<class Mem2 > constexpr CUDA battery::bitset< N, Mem, T >::bitset (const bitset< N, Mem2, T > & other) inline constexpr
Member Function Documentation
zeroes()
template<size_t N, class Mem , class T = unsigned long long> static constexpr CUDA bitset battery::bitset< N, Mem, T >::zeroes () inline static constexpr
References battery::bitset< N, Mem, T >::bitset().
ones()
template<size_t N, class Mem , class T = unsigned long long> static constexpr CUDA bitset battery::bitset< N, Mem, T >::ones () inline static constexpr
References battery::bitset< N, Mem, T >::bitset().
test()
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA bool battery::bitset< N, Mem, T >::test (size_t pos) const inline constexpr
Referenced by battery::bitset< N, Mem, T >::print(), and battery::bitset< N, Mem, T >::to_string().
all()
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA bool battery::bitset< N, Mem, T >::all () const inline constexpr
any()
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA bool battery::bitset< N, Mem, T >::any () const inline constexpr
none()
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA bool battery::bitset< N, Mem, T >::none () const inline constexpr
size()
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA size_t battery::bitset< N, Mem, T >::size () const inline constexpr
Referenced by battery::bitset< N, Mem, T >::print(), and battery::bitset< N, Mem, T >::to_string().
count()
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA size_t battery::bitset< N, Mem, T >::count () const inline constexpr
References battery::popcount().
set() [1/3]
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA bitset& battery::bitset< N, Mem, T >::set () inline constexpr
Referenced by battery::bitset< N, Mem, T >::bitset(), and battery::bitset< N, Mem, T >::set().
set() [2/3]
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA bitset& battery::bitset< N, Mem, T >::set (size_t pos) inline constexpr
set() [3/3]
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA bitset& battery::bitset< N, Mem, T >::set (size_t pos, bool value) inline constexpr
References battery::bitset< N, Mem, T >::reset(), and battery::bitset< N, Mem, T >::set().
reset() [1/2]
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA bitset& battery::bitset< N, Mem, T >::reset () inline constexpr
Referenced by battery::bitset< N, Mem, T >::set().
reset() [2/2]
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA bitset& battery::bitset< N, Mem, T >::reset (size_t pos) inline constexpr
flip() [1/2]
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA bitset& battery::bitset< N, Mem, T >::flip () inline constexpr
flip() [2/2]
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA bitset& battery::bitset< N, Mem, T >::flip (size_t pos) inline constexpr
is_subset_of()
template<size_t N, class Mem , class T = unsigned long long> template<class Mem2 > constexpr CUDA bool battery::bitset< N, Mem, T >::is_subset_of (const bitset< N, Mem2, T > & other) const inline constexpr
is_proper_subset_of()
template<size_t N, class Mem , class T = unsigned long long> template<class Mem2 > constexpr CUDA bool battery::bitset< N, Mem, T >::is_proper_subset_of (const bitset< N, Mem2, T > & other) const inline constexpr
operator&=()
template<size_t N, class Mem , class T = unsigned long long> template<class Mem2 > constexpr CUDA bitset& battery::bitset< N, Mem, T >::operator&= (const bitset< N, Mem2, T > & other) inline constexpr
operator|=()
template<size_t N, class Mem , class T = unsigned long long> template<class Mem2 > constexpr CUDA bitset& battery::bitset< N, Mem, T >::operator|= (const bitset< N, Mem2, T > & other) inline constexpr
operator^=()
template<size_t N, class Mem , class T = unsigned long long> template<class Mem2 > constexpr CUDA bitset& battery::bitset< N, Mem, T >::operator^= (const bitset< N, Mem2, T > & other) inline constexpr
operator~()
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA bitset battery::bitset< N, Mem, T >::operator~ () const inline constexpr
References battery::bitset< N, Mem, T >::bitset().
operator==()
template<size_t N, class Mem , class T = unsigned long long> template<class Mem2 > constexpr CUDA bool battery::bitset< N, Mem, T >::operator== (const bitset< N, Mem2, T > & other) const inline constexpr
operator!=()
template<size_t N, class Mem , class T = unsigned long long> template<class Mem2 > constexpr CUDA bool battery::bitset< N, Mem, T >::operator!= (const bitset< N, Mem2, T > & other) const inline constexpr
countl_zero()
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA int battery::bitset< N, Mem, T >::countl_zero () const inline constexpr
References battery::countl_zero().
countl_one()
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA int battery::bitset< N, Mem, T >::countl_one () const inline constexpr
References battery::countl_one().
countr_zero()
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA int battery::bitset< N, Mem, T >::countr_zero () const inline constexpr
References battery::countr_zero().
countr_one()
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA int battery::bitset< N, Mem, T >::countr_one () const inline constexpr
References battery::countr_one().
print()
template<size_t N, class Mem , class T = unsigned long long> constexpr CUDA void battery::bitset< N, Mem, T >::print () const inline constexpr
References battery::bitset< N, Mem, T >::size(), and battery::bitset< N, Mem, T >::test().
to_string()
template<size_t N, class Mem , class T = unsigned long long> template<class Allocator > CUDA string<Allocator> battery::bitset< N, Mem, T >::to_string (Allocator allocator = Allocator()) const inline
References battery::bitset< N, Mem, T >::size(), and battery::bitset< N, Mem, T >::test().
The documentation for this class was generated from the following file:
include/battery/bitset.hpp