Cuda battery library: battery::impl Namespace Reference
battery::impl Namespace Reference
Classes
struct variant_helper_rec
struct variant_helper_rec< n, F, Ts... >
struct variant_helper_rec< n >
struct variant_helper
struct variant_helper<>
struct variant_helper_static
struct variant_alternative
struct variant_alternative< 0, HeadItem, TailItems... >
struct variant_alternative< i, HeadItem, TailItems... >
Typedefs
template<class T >
using atomic_t = std::atomic< T >
Functions
template<class Allocator >
CUDA string< Allocator > concat (const char *lhs, size_t lhs_len, const char *rhs, size_t rhs_len, Allocator alloc)
template<class T >
constexpr CUDA void swap (T &a, T &b)
constexpr CUDA size_t strlen (const char *str)
constexpr CUDA int strcmp (const char *s1, const char *s2)
Variables
__device__ void * raw_ptr
Typedef Documentation
atomic_t
template<class T > using battery::impl::atomic_t = typedef std::atomic<T>
Function Documentation
concat()
template<class Allocator > CUDA string<Allocator> battery::impl::concat (const char * lhs, size_t lhs_len, const char * rhs, size_t rhs_len, Allocator alloc)
Referenced by battery::operator+().
swap()
template<class T > constexpr CUDA void battery::impl::swap (T & a, T & b) inline constexpr
Referenced by battery::shared_ptr< T, Allocator >::swap(), battery::swap(), battery::vector< T, Allocator >::swap(), and battery::unique_ptr< T, Allocator >::swap().
strlen()
constexpr CUDA size_t battery::impl::strlen (const char * str) inline constexpr
Referenced by battery::strlen().
strcmp()
constexpr CUDA int battery::impl::strcmp (const char * s1, const char * s2) inline constexpr
See https://stackoverflow.com/a/34873406/2231159
Referenced by battery::strcmp().
Variable Documentation
raw_ptr
__device__ void* battery::impl::raw_ptr
Referenced by battery::make_unique_block(), and battery::make_unique_grid().