Cuda battery library: battery::variant< Ts > Struct Template Reference
battery::variant< Ts > Struct Template Reference
#include <variant.hpp>
Public Member Functions
CUDA variant (const variant< Ts... > &from)
CUDA variant (variant< Ts... > &&from)
CUDA variant< Ts... > & operator= (variant< Ts... > &rhs)
CUDA variant< Ts... > & operator= (variant< Ts... > &&rhs)
CUDA size_t index () const
template<size_t i>
CUDA void set (alternative< i > &value)
template<size_t i>
CUDA void set (alternative< i > &&value)
CUDA ~variant ()
CUDA void print () const
Static Public Member Functions
template<size_t i>
static CUDA variant create (const alternative< i > &value)
template<size_t i>
static CUDA variant create (alternative< i > &&value)
Friends
template<typename... Us>
CUDA friend bool operator== (const variant< Us... > &lhs, const variant< Us... > &rhs)
template<size_t i, typename... Us>
CUDA friend impl::variant_alternative< i, Us... >::type & get (variant< Us... > &v)
template<size_t i, typename... Us>
CUDA friend const impl::variant_alternative< i, Us... >::type & get (const variant< Us... > &v)
Constructor & Destructor Documentation
variant() [1/2]
template<typename... Ts> CUDA battery::variant< Ts >::variant (const variant< Ts... > & from) inline
References battery::impl::variant_helper< Ts >::copy().
variant() [2/2]
template<typename... Ts> CUDA battery::variant< Ts >::variant (variant< Ts... > && from) inline
References battery::impl::variant_helper< Ts >::move().
~variant()
template<typename... Ts> CUDA battery::variant< Ts >::~variant () inline
References battery::impl::variant_helper< Ts >::destroy().
Member Function Documentation
create() [1/2]
template<typename... Ts> template<size_t i> static CUDA variant battery::variant< Ts >::create (const alternative< i > & value) inline static
create() [2/2]
template<typename... Ts> template<size_t i> static CUDA variant battery::variant< Ts >::create (alternative< i > && value) inline static
operator=() [1/2]
template<typename... Ts> CUDA variant<Ts...>& battery::variant< Ts >::operator= (variant< Ts... > & rhs) inline
References battery::impl::variant_helper< Ts >::copy(), and battery::impl::variant_helper< Ts >::destroy().
operator=() [2/2]
template<typename... Ts> CUDA variant<Ts...>& battery::variant< Ts >::operator= (variant< Ts... > && rhs) inline
References battery::impl::variant_helper< Ts >::destroy(), and battery::impl::variant_helper< Ts >::move().
index()
template<typename... Ts> CUDA size_t battery::variant< Ts >::index () const inline
Referenced by battery::operator==().
set() [1/2]
template<typename... Ts> template<size_t i> CUDA void battery::variant< Ts >::set (alternative< i > & value) inline
References battery::impl::variant_helper< Ts >::destroy().
set() [2/2]
template<typename... Ts> template<size_t i> CUDA void battery::variant< Ts >::set (alternative< i > && value) inline
References battery::impl::variant_helper< Ts >::destroy().
print()
template<typename... Ts> CUDA void battery::variant< Ts >::print () const inline
References battery::impl::variant_helper< Ts >::print().
Friends And Related Function Documentation
operator==
template<typename... Ts> template<typename... Us> CUDA friend bool operator== (const variant< Us... > & lhs, const variant< Us... > & rhs) friend
get [1/2]
template<typename... Ts> template<size_t i, typename... Us> CUDA friend impl::variant_alternative<i, Us...>::type& get (variant< Us... > & v) friend
get [2/2]
template<typename... Ts> template<size_t i, typename... Us> CUDA friend const impl::variant_alternative<i, Us...>::type& get (const variant< Us... > & v) friend
The documentation for this struct was generated from the following file:
include/battery/variant.hpp