Cuda battery library: String< Allocator > Class Template Reference
String< Allocator > Class Template Reference
#include <string.hpp>
Public Types
typedef String< Allocator > this_type
Public Member Functions
CUDA String (size_t n, const Allocator &alloc=Allocator())
CUDA DArray (size_t n, const T *from, const Allocator &alloc=Allocator())
template<typename Allocator2 >
CUDA DArray (const DArray< T, Allocator2 > &from, const Allocator &alloc=Allocator())
CUDA DArray (const DArray< T, Allocator > &from)
CUDA DArray (size_t n, const T &from, const Allocator &alloc=Allocator())
HOST DArray (const std::vector< T > &from, const Allocator &alloc=Allocator())
CUDA ~DArray ()
CUDA size_t size () const
CUDA T & operator[] (size_t i)
const CUDA T & operator[] (size_t i) const
CUDA T * data ()
const CUDA T * data () const
Detailed Description
template<typename Allocator>
class String< Allocator >
String represents a fixed sized array of characters based on DArray<char> (see darray.hpp).
Member Typedef Documentation
this_type
template<typename Allocator > typedef String<Allocator> String< Allocator >::this_type
Constructor & Destructor Documentation
String()
template<typename Allocator > CUDA String< Allocator >::String (size_t n, const Allocator & alloc = Allocator()) inline
Allocate a string of size n using allocator.
~DArray()
template<typename Allocator > CUDA String< Allocator >::~DArray () inline
References impl::TypeAllocatorDispatch< T >::destroy().
Member Function Documentation
DArray() [1/5]
template<typename Allocator > CUDA String< Allocator >::DArray (size_t n, const T * from, const Allocator & alloc = Allocator()) inline
Allocate an array of size n using allocator. Initialize the elements of the array with those of from.
References impl::TypeAllocatorDispatch< T >::build().
DArray() [2/5]
template<typename Allocator > template<typename Allocator2 > CUDA String< Allocator >::DArray (const DArray< T, Allocator2 > & from, const Allocator & alloc = Allocator()) inline
Copy constructor with an allocator.
DArray() [3/5]
template<typename Allocator > CUDA String< Allocator >::DArray (const DArray< T, Allocator > & from) inline
Redefine the copy constructor to be sure it calls a constructor with an allocator.
DArray() [4/5]
template<typename Allocator > CUDA String< Allocator >::DArray (size_t n, const T & from, const Allocator & alloc = Allocator()) inline
Initialize of an array of size n with each element initialized to from using allocator.
References impl::TypeAllocatorDispatch< T >::build().
DArray() [5/5]
template<typename Allocator > HOST String< Allocator >::DArray (const std::vector< T > & from, const Allocator & alloc = Allocator()) inline
size()
template<typename Allocator > CUDA size_t String< Allocator >::size () const inline
operator[]() [1/2]
template<typename Allocator > CUDA T& String< Allocator >::operator[] (size_t i) inline
operator[]() [2/2]
template<typename Allocator > const CUDA T& String< Allocator >::operator[] (size_t i) const inline
data() [1/2]
template<typename Allocator > CUDA T* String< Allocator >::data () inline
data() [2/2]
template<typename Allocator > const CUDA T* String< Allocator >::data () const inline
The documentation for this class was generated from the following file:
include/string.hpp