Cuda battery library: battery::vector< T, Allocator > Class Template Reference
battery::vector< T, Allocator > Class Template Reference
#include <vector.hpp>
Public Types
using value_type = T
using allocator_type = Allocator
using this_type = vector< value_type, allocator_type >
Public Member Functions
CUDA vector (size_t n, const allocator_type &alloc=allocator_type())
CUDA vector (const allocator_type &alloc=allocator_type())
template<class U >
CUDA vector (const U *from, size_t n, const allocator_type &alloc=allocator_type())
template<class U , class Allocator2 >
CUDA vector (const vector< U, Allocator2 > &from, const allocator_type &alloc=allocator_type())
CUDA vector (const this_type &from)
template<class U >
CUDA vector (size_t n, const U &from, const allocator_type &alloc=allocator_type())
CUDA vector (this_type &&other)
CUDA vector (std::initializer_list< T > init, const Allocator &alloc=Allocator())
CUDA ~vector ()
CUDA this_type & operator= (this_type &&other)
CUDA this_type & operator= (const this_type &other)
CUDA allocator_type get_allocator () const
CUDA value_type & operator[] (size_t i)
const CUDA value_type & operator[] (size_t i) const
CUDA value_type & front ()
const CUDA value_type & front () const
CUDA value_type & back ()
const CUDA value_type & back () const
CUDA value_type * data ()
const CUDA value_type * data () const
CUDA bool empty () const
CUDA size_t size () const
CUDA void reserve (size_t new_cap)
CUDA size_t capacity () const
CUDA void shrink_to_fit ()
CUDA void clear ()
CUDA void push_back (const T &value)
CUDA void push_back (T &&value)
template<class... Args>
CUDA value_type & emplace_back (Args &&... args)
CUDA void pop_back ()
CUDA void resize (size_t count)
CUDA void swap (this_type &other)
CUDA void print () const
Friends
template<class T2 , class Allocator2 >
class vector
Member Typedef Documentation
value_type
template<class T , class Allocator = StandardAllocator> using battery::vector< T, Allocator >::value_type = T
allocator_type
template<class T , class Allocator = StandardAllocator> using battery::vector< T, Allocator >::allocator_type = Allocator
this_type
template<class T , class Allocator = StandardAllocator> using battery::vector< T, Allocator >::this_type = vector<value_type, allocator_type>
Constructor & Destructor Documentation
vector() [1/8]
template<class T , class Allocator = StandardAllocator> CUDA battery::vector< T, Allocator >::vector (size_t n, const allocator_type & alloc = allocator_type()) inline
Allocate an array of size n using allocator, with n default-inserted instances of T. Allocator is scoped, meaning it will be passed to the constructor of T if T(const Allocator&) exists, otherwise T() is called.
vector() [2/8]
template<class T , class Allocator = StandardAllocator> CUDA battery::vector< T, Allocator >::vector (const allocator_type & alloc = allocator_type()) inline
Default constructor.
vector() [3/8]
template<class T , class Allocator = StandardAllocator> template<class U > CUDA battery::vector< T, Allocator >::vector (const U * from, size_t n, const allocator_type & alloc = allocator_type()) inline
Allocate an array of size n using allocator. Initialize the elements of the array with those of the array from. Allocator is scoped, meaning it will be passed to the constructor of T if T(const T&, const Allocator&) exists, otherwise T(const T&) is called.
vector() [4/8]
template<class T , class Allocator = StandardAllocator> template<class U , class Allocator2 > CUDA battery::vector< T, Allocator >::vector (const vector< U, Allocator2 > & from, const allocator_type & alloc = allocator_type()) inline
Copy constructor with an allocator, useful when the vector we copied from was declared using another allocator.
vector() [5/8]
template<class T , class Allocator = StandardAllocator> CUDA battery::vector< T, Allocator >::vector (const this_type & from) inline
Redefine the copy constructor to be sure it calls a constructor with an allocator.
vector() [6/8]
template<class T , class Allocator = StandardAllocator> template<class U > CUDA battery::vector< T, Allocator >::vector (size_t n, const U & from, const allocator_type & alloc = allocator_type()) inline
Initialize of an array of size n with each element initialized to from using allocator. Allocator is scoped, meaning it will be passed to the constructor of T if T(const T&, const Allocator&) exists, otherwise T(const T&) is called.
vector() [7/8]
template<class T , class Allocator = StandardAllocator> CUDA battery::vector< T, Allocator >::vector (this_type && other) inline
vector() [8/8]
template<class T , class Allocator = StandardAllocator> CUDA battery::vector< T, Allocator >::vector (std::initializer_list< T > init, const Allocator & alloc = Allocator()) inline
~vector()
template<class T , class Allocator = StandardAllocator> CUDA battery::vector< T, Allocator >::~vector () inline
Member Function Documentation
operator=() [1/2]
template<class T , class Allocator = StandardAllocator> CUDA this_type& battery::vector< T, Allocator >::operator= (this_type && other) inline
operator=() [2/2]
template<class T , class Allocator = StandardAllocator> CUDA this_type& battery::vector< T, Allocator >::operator= (const this_type & other) inline
get_allocator()
template<class T , class Allocator = StandardAllocator> CUDA allocator_type battery::vector< T, Allocator >::get_allocator () const inline
Referenced by battery::String< Allocator >::get_allocator().
operator[]() [1/2]
template<class T , class Allocator = StandardAllocator> CUDA value_type& battery::vector< T, Allocator >::operator[] (size_t i) inline
operator[]() [2/2]
template<class T , class Allocator = StandardAllocator> const CUDA value_type& battery::vector< T, Allocator >::operator[] (size_t i) const inline
front() [1/2]
template<class T , class Allocator = StandardAllocator> CUDA value_type& battery::vector< T, Allocator >::front () inline
front() [2/2]
template<class T , class Allocator = StandardAllocator> const CUDA value_type& battery::vector< T, Allocator >::front () const inline
back() [1/2]
template<class T , class Allocator = StandardAllocator> CUDA value_type& battery::vector< T, Allocator >::back () inline
back() [2/2]
template<class T , class Allocator = StandardAllocator> const CUDA value_type& battery::vector< T, Allocator >::back () const inline
data() [1/2]
template<class T , class Allocator = StandardAllocator> CUDA value_type* battery::vector< T, Allocator >::data () inline
Referenced by battery::String< Allocator >::data().
data() [2/2]
template<class T , class Allocator = StandardAllocator> const CUDA value_type* battery::vector< T, Allocator >::data () const inline
empty()
template<class T , class Allocator = StandardAllocator> CUDA bool battery::vector< T, Allocator >::empty () const inline
size()
template<class T , class Allocator = StandardAllocator> CUDA size_t battery::vector< T, Allocator >::size () const inline
Referenced by battery::vector< char, Allocator >::operator=(), battery::operator==(), and battery::String< Allocator >::size().
reserve()
template<class T , class Allocator = StandardAllocator> CUDA void battery::vector< T, Allocator >::reserve (size_t new_cap) inline
Referenced by battery::vector< char, Allocator >::operator=().
capacity()
template<class T , class Allocator = StandardAllocator> CUDA size_t battery::vector< T, Allocator >::capacity () const inline
shrink_to_fit()
template<class T , class Allocator = StandardAllocator> CUDA void battery::vector< T, Allocator >::shrink_to_fit () inline
clear()
template<class T , class Allocator = StandardAllocator> CUDA void battery::vector< T, Allocator >::clear () inline
push_back() [1/2]
template<class T , class Allocator = StandardAllocator> CUDA void battery::vector< T, Allocator >::push_back (const T & value) inline
push_back() [2/2]
template<class T , class Allocator = StandardAllocator> CUDA void battery::vector< T, Allocator >::push_back (T && value) inline
emplace_back()
template<class T , class Allocator = StandardAllocator> template<class... Args> CUDA value_type& battery::vector< T, Allocator >::emplace_back (Args &&... args) inline
pop_back()
template<class T , class Allocator = StandardAllocator> CUDA void battery::vector< T, Allocator >::pop_back () inline
resize()
template<class T , class Allocator = StandardAllocator> CUDA void battery::vector< T, Allocator >::resize (size_t count) inline
swap()
template<class T , class Allocator = StandardAllocator> CUDA void battery::vector< T, Allocator >::swap (this_type & other) inline
Referenced by battery::vector< char, Allocator >::operator=(), and battery::vector< char, Allocator >::vector().
print()
template<class T , class Allocator = StandardAllocator> CUDA void battery::vector< T, Allocator >::print () const inline
Friends And Related Function Documentation
vector
template<class T , class Allocator = StandardAllocator> template<class T2 , class Allocator2 > friend class vector friend
The documentation for this class was generated from the following file:
include/vector.hpp