Cuda battery library: battery Namespace Reference
battery Namespace Reference
Namespaces
impl
Classes
class AtomicMemory
class Bitset
struct Limits
class LocalMemory
class Memory
class PoolAllocator
class shared_ptr
class StandardAllocator
class String
class unique_ptr
struct variant
class vector
Typedefs
template<class Allocator >
using ReadOnlyMemory = Memory< Allocator, true >
using memory_order = std::memory_order
Functions
template<size_t N, class Mem , class T >
Bitset< N, Mem, T > operator& (const Bitset< N, Mem, T > &lhs, const Bitset< N, Mem, T > &rhs)
template<size_t N, class Mem , class T >
Bitset< N, Mem, T > operator| (const Bitset< N, Mem, T > &lhs, const Bitset< N, Mem, T > &rhs)
template<size_t N, class Mem , class T >
Bitset< N, Mem, T > operator^ (const Bitset< N, Mem, T > &lhs, const Bitset< N, Mem, T > &rhs)
template<class T , class Alloc , class... Args>
CUDA shared_ptr< T, Alloc > allocate_shared (const Alloc &alloc, Args &&... args)
template<class T , class Alloc , class... Args>
CUDA shared_ptr< T, Alloc > make_shared (Args &&... args)
template<class Allocator >
CUDA bool operator== (const String< Allocator > &lhs, const String< Allocator > &rhs)
template<class Allocator >
CUDA bool operator== (const char *lhs, const String< Allocator > &rhs)
template<class Allocator >
CUDA bool operator== (const String< Allocator > &lhs, const char *rhs)
template<class Allocator >
CUDA bool operator!= (const String< Allocator > &lhs, const String< Allocator > &rhs)
template<class Allocator >
CUDA bool operator!= (const char *lhs, const String< Allocator > &rhs)
template<class Allocator >
CUDA bool operator!= (const String< Allocator > &lhs, const char *rhs)
template<class Allocator >
CUDA String< Allocator > operator+ (const String< Allocator > &lhs, const String< Allocator > &rhs)
template<class Allocator >
CUDA String< Allocator > operator+ (const char *lhs, const String< Allocator > &rhs)
template<class Allocator >
CUDA String< Allocator > operator+ (const String< Allocator > &lhs, const char *rhs)
template<class T , class Alloc , class... Args>
CUDA unique_ptr< T, Alloc > allocate_unique (const Alloc &alloc, Args &&... args)
template<class T , class Alloc , class... Args>
CUDA unique_ptr< T, Alloc > make_unique (Args &&... args)
template<class T >
CUDA void swap (T &a, T &b)
CUDA size_t strlen (const char *str)
CUDA int strcmp (const char *s1, const char *s2)
template<class T >
CUDA T min (T a, T b)
template<class T >
CUDA T max (T a, T b)
template<class T >
CUDA T isnan (T a)
CUDA float nextafter (float f, float dir)
CUDA double nextafter (double f, double dir)
template<class To , class From >
CUDA To ru_cast (From x)
template<class To , class From >
CUDA To rd_cast (From x)
template<class T >
CUDA int popcount (T x)
template<class T >
CUDA int countl_zero (T x)
template<class T >
CUDA int countl_one (T x)
template<class T >
CUDA int countr_zero (T x)
template<class T >
CUDA int countr_one (T x)
template<class T >
CUDA int signum (T val)
template<class T >
CUDA T ipow (T a, T b)
template<class T >
CUDA T add_up (T x, T y)
template<class T >
CUDA T add_down (T x, T y)
template<class T >
CUDA T sub_up (T x, T y)
template<class T >
CUDA T sub_down (T x, T y)
template<class T >
CUDA T mul_up (T x, T y)
template<class T >
CUDA T mul_down (T x, T y)
template<class T >
CUDA T div_up (T x, T y)
template<class T >
CUDA T div_down (T x, T y)
template<typename T >
CUDA void print (const T &t)
template<>
CUDA void print (const char &x)
template<>
CUDA void print (const short &x)
template<>
CUDA void print (const int &x)
template<>
CUDA void print (const long long int &x)
template<>
CUDA void print (const long int &x)
template<>
CUDA void print (const unsigned char &x)
template<>
CUDA void print (const unsigned short &x)
template<>
CUDA void print (const unsigned int &x)
template<>
CUDA void print (const unsigned long &x)
template<>
CUDA void print (const unsigned long long &x)
template<>
CUDA void print (const float &x)
template<>
CUDA void print (const double &x)
template<>
CUDA void print (char const *const &x)
template<size_t i, typename... Ts>
CUDA impl::variant_alternative< i, Ts... >::type & get (variant< Ts... > &v)
template<size_t i, typename... Ts>
const CUDA impl::variant_alternative< i, Ts... >::type & get (const variant< Ts... > &v)
template<typename... Ts>
CUDA bool operator== (const variant< Ts... > &lhs, const variant< Ts... > &rhs)
template<typename... Ts>
CUDA bool operator!= (const variant< Ts... > &lhs, const variant< Ts... > &rhs)
template<class T , class Allocator >
CUDA bool operator== (const vector< T, Allocator > &lhs, const vector< T, Allocator > &rhs)
template<class T , class Allocator >
CUDA bool operator!= (const vector< T, Allocator > &lhs, const vector< T, Allocator > &rhs)
Variables
constexpr memory_order memory_order_relaxed = std::memory_order_relaxed
constexpr memory_order memory_order_seq_cst = std::memory_order_seq_cst
Detailed Description
An abstraction of memory useful to write a single version of an algorithm working either sequentially or in parallel, and on CPU or GPU.
Typedef Documentation
ReadOnlyMemory
template<class Allocator > using battery::ReadOnlyMemory = typedef Memory<Allocator, true>
memory_order
using battery::memory_order = typedef std::memory_order
Function Documentation
operator&()
template<size_t N, class Mem , class T > Bitset<N, Mem, T> battery::operator& (const Bitset< N, Mem, T > & lhs, const Bitset< N, Mem, T > & rhs)
operator|()
template<size_t N, class Mem , class T > Bitset<N, Mem, T> battery::operator| (const Bitset< N, Mem, T > & lhs, const Bitset< N, Mem, T > & rhs)
operator^()
template<size_t N, class Mem , class T > Bitset<N, Mem, T> battery::operator^ (const Bitset< N, Mem, T > & lhs, const Bitset< N, Mem, T > & rhs)
allocate_shared()
template<class T , class Alloc , class... Args> CUDA shared_ptr<T, Alloc> battery::allocate_shared (const Alloc & alloc, Args &&... args)
make_shared()
template<class T , class Alloc , class... Args> CUDA shared_ptr<T, Alloc> battery::make_shared (Args &&... args)
Similar to allocate_shared but with an default-constructed allocator.
operator==() [1/5]
template<class Allocator > CUDA bool battery::operator== (const String< Allocator > & lhs, const String< Allocator > & rhs)
References battery::String< Allocator >::data(), battery::String< Allocator >::size(), and strcmp().
operator==() [2/5]
template<class Allocator > CUDA bool battery::operator== (const char * lhs, const String< Allocator > & rhs)
References battery::String< Allocator >::data(), and strcmp().
operator==() [3/5]
template<class Allocator > CUDA bool battery::operator== (const String< Allocator > & lhs, const char * rhs)
References battery::String< Allocator >::data(), and strcmp().
operator!=() [1/5]
template<class Allocator > CUDA bool battery::operator!= (const String< Allocator > & lhs, const String< Allocator > & rhs)
operator!=() [2/5]
template<class Allocator > CUDA bool battery::operator!= (const char * lhs, const String< Allocator > & rhs)
operator!=() [3/5]
template<class Allocator > CUDA bool battery::operator!= (const String< Allocator > & lhs, const char * rhs)
operator+() [1/3]
template<class Allocator > CUDA String<Allocator> battery::operator+ (const String< Allocator > & lhs, const String< Allocator > & rhs)
References battery::impl::concat(), battery::String< Allocator >::data(), battery::String< Allocator >::get_allocator(), and battery::String< Allocator >::size().
operator+() [2/3]
template<class Allocator > CUDA String<Allocator> battery::operator+ (const char * lhs, const String< Allocator > & rhs)
References battery::impl::concat(), battery::String< Allocator >::data(), battery::String< Allocator >::get_allocator(), battery::String< Allocator >::size(), and strlen().
operator+() [3/3]
template<class Allocator > CUDA String<Allocator> battery::operator+ (const String< Allocator > & lhs, const char * rhs)
References battery::impl::concat(), battery::String< Allocator >::data(), battery::String< Allocator >::get_allocator(), battery::String< Allocator >::size(), and strlen().
allocate_unique()
template<class T , class Alloc , class... Args> CUDA unique_ptr<T, Alloc> battery::allocate_unique (const Alloc & alloc, Args &&... args)
make_unique()
template<class T , class Alloc , class... Args> CUDA unique_ptr<T, Alloc> battery::make_unique (Args &&... args)
Similar to allocate_unique but with an default-constructed allocator.
swap()
template<class T > CUDA void battery::swap (T & a, T & b) inline
References battery::impl::swap().
strlen()
CUDA size_t battery::strlen (const char * str) inline
References battery::impl::strlen().
Referenced by battery::Bitset< N, Mem, T >::Bitset(), and operator+().
strcmp()
CUDA int battery::strcmp (const char * s1, const char * s2) inline
See https://stackoverflow.com/a/34873406/2231159
References battery::impl::strcmp().
Referenced by operator==().
min()
template<class T > CUDA T battery::min (T a, T b)
Referenced by battery::Bitset< N, Mem, T >::Bitset(), and battery::Limits< T >::bot().
max()
template<class T > CUDA T battery::max (T a, T b)
Referenced by battery::Limits< T >::top().
isnan()
template<class T > CUDA T battery::isnan (T a)
nextafter() [1/2]
CUDA float battery::nextafter (float f, float dir) inline
nextafter() [2/2]
CUDA double battery::nextafter (double f, double dir) inline
ru_cast()
template<class To , class From > CUDA To battery::ru_cast (From x)
Cast the variable x from type From to type To following upper rounding rule (cast in the direction of infinity). Minimal and maximal values of From are interpreted as infinities, and are therefore mapped to the infinities of the new types accordingly (e.g., float INF maps to int MAX_INT).
On CPU: Rounding mode is UPWARD after this operation. On GPU: CUDA intrinsics are used.
Overflow: Nothing is done to prevent overflow, it mostly behaves as with static_cast.
References MAP_LIMITS.
rd_cast()
template<class To , class From > CUDA To battery::rd_cast (From x)
Cast the variable x from type From to type To following down rounding rule (cast in the direction of negative infinity). Minimal and maximal values of From are interpreted as infinities, and are therefore mapped to the infinities of the new types accordingly (e.g., float INF maps to int MAX_INT).
On CPU: Rounding mode is DOWNWARD after this operation. On GPU: CUDA intrinsics are used.
Overflow: Nothing is done to prevent overflow, it mostly behaves as with static_cast.
References MAP_LIMITS.
popcount()
template<class T > CUDA int battery::popcount (T x)
Referenced by battery::Bitset< N, Mem, T >::count().
countl_zero()
template<class T > CUDA int battery::countl_zero (T x)
Referenced by countl_one(), and battery::Bitset< N, Mem, T >::countl_zero().
countl_one()
template<class T > CUDA int battery::countl_one (T x)
References countl_zero().
Referenced by battery::Bitset< N, Mem, T >::countl_one().
countr_zero()
template<class T > CUDA int battery::countr_zero (T x)
Referenced by countr_one(), and battery::Bitset< N, Mem, T >::countr_zero().
countr_one()
template<class T > CUDA int battery::countr_one (T x)
References countr_zero().
Referenced by battery::Bitset< N, Mem, T >::countr_one().
signum()
template<class T > CUDA int battery::signum (T val)
Signum function, https://stackoverflow.com/a/4609795/2231159
ipow()
template<class T > CUDA T battery::ipow (T a, T b)
Precondition: T is an integer with b >= 0.
add_up()
template<class T > CUDA T battery::add_up (T x, T y)
References FLOAT_ARITHMETIC_CPP_IMPL, and FLOAT_ARITHMETIC_CUDA_IMPL.
add_down()
template<class T > CUDA T battery::add_down (T x, T y)
References FLOAT_ARITHMETIC_CPP_IMPL, and FLOAT_ARITHMETIC_CUDA_IMPL.
sub_up()
template<class T > CUDA T battery::sub_up (T x, T y)
References FLOAT_ARITHMETIC_CPP_IMPL, and FLOAT_ARITHMETIC_CUDA_IMPL.
sub_down()
template<class T > CUDA T battery::sub_down (T x, T y)
References FLOAT_ARITHMETIC_CPP_IMPL, and FLOAT_ARITHMETIC_CUDA_IMPL.
mul_up()
template<class T > CUDA T battery::mul_up (T x, T y)
References FLOAT_ARITHMETIC_CPP_IMPL, and FLOAT_ARITHMETIC_CUDA_IMPL.
mul_down()
template<class T > CUDA T battery::mul_down (T x, T y)
References FLOAT_ARITHMETIC_CPP_IMPL, and FLOAT_ARITHMETIC_CUDA_IMPL.
div_up()
template<class T > CUDA T battery::div_up (T x, T y)
References FLOAT_ARITHMETIC_CPP_IMPL, and FLOAT_ARITHMETIC_CUDA_IMPL.
div_down()
template<class T > CUDA T battery::div_down (T x, T y)
References FLOAT_ARITHMETIC_CPP_IMPL, and FLOAT_ARITHMETIC_CUDA_IMPL.
print() [1/14]
template<typename T > CUDA void battery::print (const T & t) inline
Referenced by battery::impl::variant_helper_rec< n, F, Ts... >::print(), battery::impl::variant_helper< Ts >::print(), and battery::vector< char, Allocator >::print().
print() [2/14]
template<> CUDA void battery::print (const char & x) inline
print() [3/14]
template<> CUDA void battery::print (const short & x) inline
print() [4/14]
template<> CUDA void battery::print (const int & x) inline
print() [5/14]
template<> CUDA void battery::print (const long long int & x) inline
print() [6/14]
template<> CUDA void battery::print (const long int & x) inline
print() [7/14]
template<> CUDA void battery::print (const unsigned char & x) inline
print() [8/14]
template<> CUDA void battery::print (const unsigned short & x) inline
print() [9/14]
template<> CUDA void battery::print (const unsigned int & x) inline
print() [10/14]
template<> CUDA void battery::print (const unsigned long & x) inline
print() [11/14]
template<> CUDA void battery::print (const unsigned long long & x) inline
print() [12/14]
template<> CUDA void battery::print (const float & x) inline
print() [13/14]
template<> CUDA void battery::print (const double & x) inline
print() [14/14]
template<> CUDA void battery::print (char const *const & x) inline
get() [1/2]
template<size_t i, typename... Ts> CUDA impl::variant_alternative<i, Ts...>::type& battery::get (variant< Ts... > & v)
get() [2/2]
template<size_t i, typename... Ts> const CUDA impl::variant_alternative<i, Ts...>::type& battery::get (const variant< Ts... > & v)
operator==() [4/5]
template<typename... Ts> CUDA bool battery::operator== (const variant< Ts... > & lhs, const variant< Ts... > & rhs)
References battery::impl::variant_helper< Ts >::equals(), and battery::variant< Ts >::index().
operator!=() [4/5]
template<typename... Ts> CUDA bool battery::operator!= (const variant< Ts... > & lhs, const variant< Ts... > & rhs)
operator==() [5/5]
template<class T , class Allocator > CUDA bool battery::operator== (const vector< T, Allocator > & lhs, const vector< T, Allocator > & rhs)
References battery::vector< T, Allocator >::size().
operator!=() [5/5]
template<class T , class Allocator > CUDA bool battery::operator!= (const vector< T, Allocator > & lhs, const vector< T, Allocator > & rhs)
Variable Documentation
memory_order_relaxed
constexpr memory_order battery::memory_order_relaxed = std::memory_order_relaxed constexpr
memory_order_seq_cst
constexpr memory_order battery::memory_order_seq_cst = std::memory_order_seq_cst constexpr