Cuda battery library: battery::impl::variant_helper< Ts > Struct Template Reference
battery::impl::variant_helper< Ts > Struct Template Reference
#include <variant.hpp>
Static Public Member Functions
static CUDA void destroy (size_t id, void *data)
static CUDA void move (size_t id, void *from, void *to)
static CUDA void copy (size_t id, const void *from, void *to)
static CUDA bool equals (size_t id, const void *a, const void *b)
static CUDA void print (size_t id, const void *a)
Member Function Documentation
destroy()
template<typename... Ts> static CUDA void battery::impl::variant_helper< Ts >::destroy (size_t id, void * data) inline static
Referenced by battery::variant< Ts >::operator=(), battery::variant< Ts >::set(), and battery::variant< Ts >::~variant().
move()
template<typename... Ts> static CUDA void battery::impl::variant_helper< Ts >::move (size_t id, void * from, void * to) inline static
Referenced by battery::variant< Ts >::operator=(), and battery::variant< Ts >::variant().
copy()
template<typename... Ts> static CUDA void battery::impl::variant_helper< Ts >::copy (size_t id, const void * from, void * to) inline static
Referenced by battery::variant< Ts >::operator=(), and battery::variant< Ts >::variant().
equals()
template<typename... Ts> static CUDA bool battery::impl::variant_helper< Ts >::equals (size_t id, const void * a, const void * b) inline static
Referenced by battery::operator==().
print()
template<typename... Ts> static CUDA void battery::impl::variant_helper< Ts >::print (size_t id, const void * a) inline static
References battery::print().
Referenced by battery::variant< Ts >::print().
The documentation for this struct was generated from the following file:
include/variant.hpp