Lattice land core library: lala::ZInc< VT, Alloc > Class Template Reference
lala::ZInc< VT, Alloc > Class Template Reference
#include <z.hpp>
Public Types
typedef VT ValueType
typedef Alloc Allocator
typedef ZInc< ValueType, Allocator > this_type
typedef ZInc LogicalElement
Public Member Functions
CUDA operator ValueType () const
template<typename VT2 >
CUDA ZInc (VT2 i)
template<typename Allocator2 >
CUDA ZInc (const ZInc< ValueType, Allocator2 > &i)
CUDA ZInc (const this_type &i)
CUDA bool operator== (const this_type &other) const
CUDA thrust::optional< LogicalElement > interpret (Approx appx, const Formula &f)
CUDA this_type & join (const LogicalElement &other)
CUDA this_type & meet (const LogicalElement &other)
CUDA bool refine ()
CUDA bool entailment (const LogicalElement &other) const
template<typename Allocator >
CUDA DArray< LogicalElement, Allocator > split (Allocator &allocator) const
CUDA bool is_underappx () const
CUDA void reset (const this_type &other)
CUDA this_type clone () const
template<typename Allocator >
CUDA Formula deinterpret (Allocator &allocator) const
CUDA void print () const
Static Public Member Functions
static CUDA ZInc bot ()
static CUDA ZInc top ()
Detailed Description
template<typename VT, typename Alloc>
class lala::ZInc< VT, Alloc >
The lattice of increasing integers.
Member Typedef Documentation
ValueType
template<typename VT , typename Alloc > typedef VT lala::ZInc< VT, Alloc >::ValueType
Allocator
template<typename VT , typename Alloc > typedef Alloc lala::ZInc< VT, Alloc >::Allocator
this_type
template<typename VT , typename Alloc > typedef ZInc<ValueType, Allocator> lala::ZInc< VT, Alloc >::this_type
LogicalElement
template<typename VT , typename Alloc > typedef ZInc lala::ZInc< VT, Alloc >::LogicalElement
Constructor & Destructor Documentation
ZInc() [1/3]
template<typename VT , typename Alloc > template<typename VT2 > CUDA lala::ZInc< VT, Alloc >::ZInc (VT2 i) inline
Similar to \([\![x \geq i]\!]\) for any name x.
References lala::ZInc< VT, Alloc >::bot(), and lala::ZInc< VT, Alloc >::top().
ZInc() [2/3]
template<typename VT , typename Alloc > template<typename Allocator2 > CUDA lala::ZInc< VT, Alloc >::ZInc (const ZInc< ValueType, Allocator2 > & i) inline
ZInc() [3/3]
template<typename VT , typename Alloc > CUDA lala::ZInc< VT, Alloc >::ZInc (const this_type & i) inline
Member Function Documentation
bot()
template<typename VT , typename Alloc > static CUDA ZInc lala::ZInc< VT, Alloc >::bot () inline static
Similar to \([\![\mathit{true}]\!]\).
Referenced by lala::ZInc< VT, Alloc >::interpret(), lala::ZInc< VT, Alloc >::print(), and lala::ZInc< VT, Alloc >::ZInc().
top()
template<typename VT , typename Alloc > static CUDA ZInc lala::ZInc< VT, Alloc >::top () inline static
Similar to \([\![\mathit{false}]\!]\).
Referenced by lala::ZInc< VT, Alloc >::interpret(), lala::ZInc< VT, Alloc >::print(), lala::ZInc< VT, Alloc >::split(), and lala::ZInc< VT, Alloc >::ZInc().
operator ValueType()
template<typename VT , typename Alloc > CUDA lala::ZInc< VT, Alloc >::operator ValueType () const inline explicit
operator==()
template<typename VT , typename Alloc > CUDA bool lala::ZInc< VT, Alloc >::operator== (const this_type & other) const inline
interpret()
template<typename VT , typename Alloc > CUDA thrust::optional<LogicalElement> lala::ZInc< VT, Alloc >::interpret (Approx appx, const Formula & f) inline
Expects a predicate of the form x <op> i where x is any variable's name, and i an integer.
If appx is EXACT: op can be >= or >.
If appx is UNDER: op can be >=, > or !=.
If appx is OVER: op can be >=, > or ==. An empty optional is also returned if the element would overflow in int_type.
References lala::ZInc< VT, Alloc >::bot(), lala::Formula::children, lala::Formula::i, lala::OVER, SHAPE, lala::Formula::tag, lala::ZInc< VT, Alloc >::top(), and lala::UNDER.
join()
template<typename VT , typename Alloc > CUDA this_type& lala::ZInc< VT, Alloc >::join (const LogicalElement & other) inline
\(a \sqcup b = \mathit{max}(a,b) \).
meet()
template<typename VT , typename Alloc > CUDA this_type& lala::ZInc< VT, Alloc >::meet (const LogicalElement & other) inline
\(a \sqcap b = \mathit{min}(a,b) \).
refine()
template<typename VT , typename Alloc > CUDA bool lala::ZInc< VT, Alloc >::refine () inline
Has no effect.
Returns
true.
entailment()
template<typename VT , typename Alloc > CUDA bool lala::ZInc< VT, Alloc >::entailment (const LogicalElement & other) const inline
\(a \models \varphi \) is defined as \(a \geq [\![\varphi]\!] \).
split()
template<typename VT , typename Alloc > template<typename Allocator > CUDA DArray<LogicalElement, Allocator> lala::ZInc< VT, Alloc >::split (Allocator & allocator) const inline
References lala::ZInc< VT, Alloc >::top().
is_underappx()
template<typename VT , typename Alloc > CUDA bool lala::ZInc< VT, Alloc >::is_underappx () const inline
An abstract domain can be eventually under-approximating which means that after a sufficient number of split and refine operations, it always reach an under-approximating element.
Returns
true if \(\gamma(a) \subseteq [\![\varphi]\!]^\flat\). false is returned whenever a is an over-approximation or if we do not know whether a is an under-approximation.
reset()
template<typename VT , typename Alloc > CUDA void lala::ZInc< VT, Alloc >::reset (const this_type & other) inline
Reset the internal counter to the one of other.
clone()
template<typename VT , typename Alloc > CUDA this_type lala::ZInc< VT, Alloc >::clone () const inline
Returns
A copy of the current abstract element.
deinterpret()
template<typename VT , typename Alloc > template<typename Allocator > CUDA Formula lala::ZInc< VT, Alloc >::deinterpret (Allocator & allocator) const inline
Returns
\(_ \geq i \) where _ is an arbitrary variable's name and i the integer value.
References lala::Formula::GEQ, and lala::make_x_op_i().
print()
template<typename VT , typename Alloc > CUDA void lala::ZInc< VT, Alloc >::print () const inline
Print the current element with the logical name of the variables.
References lala::ZInc< VT, Alloc >::bot(), and lala::ZInc< VT, Alloc >::top().
The documentation for this class was generated from the following file:
include/z.hpp